db:
  username: ${DATABASE_POSTGRES_USERNAME:makersweb}
  password: ${DATABASE_POSTGRES_PASSWORD:Salmos89}
  schema: adm_videos
  url: ${DATABASE_POSTGRES_URL:localhost:5432}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none