version: "3.8"
services:

  postgres_db:
    container_name: postgres_db
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Salmos89
      - POSTGRES_USER=makersweb
    volumes:
      - '../.docker/db/data:/var/lib/postgresql/data'
    networks:
      - ms-network

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - '../.docker/rabbitmqdata:/var/lib/rabbitmq/mnesia'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge